version: '3.8'

services:
  pg_backup:
    image: prodrigestivill/postgres-backup-local
    container_name: pg_backup
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BACKUP_DIR=/backups
      - SCHEDULE=${SCHEDULE}
      - BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS}
      - BACKUP_SUFFIX=.sql
      - POSTGRES_EXTRA_OPTS=-Z9
    volumes:
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - backup_network

networks:
  backup_network:
    external: true
